### ISSUE TITLE
Anonymous bind?

### ISSUE THREAD

**Issue by ghost** [Goonswarm/murmur_ldap_auth#2]
This is a question rather than an issue. Based on the source code, it looks like this authenticator tries to bind to the LDAP server with the provided credentials. Is this the case, or is anonymous bind always used?

**Comment by tazjin** [comment]
There's two separate binds going on:

1. A connection in the connection pool is bound anonymously to provide user search functionality with the configured filters.

2. When authenticating a user, a random connection from the pool is (attempted to be) [bound](https://github.com/Goonswarm/murmur_ldap_auth/blob/master/src/main/java/com/tendollarbond/murmur_ldap_auth/LDAPAuthenticator.java#L119) with the user's credentials and then released as defunct (i.e. closed)

The lifecycle of any given connection is therefore something like this:

![Connection lifecycle](https://user-images.githubusercontent.com/1552853/35039245-8b99f41a-fb7d-11e7-8f5c-0571bfb5f1d9.png)

Does that answer your question?

**Comment by ghost** [comment]
Yes, that does, thank you! I've got some followups though.

1. If the server prohibits anonymous binds, murmur_ldap_auth will no longer work, correct?

2. Why not simply try to bind with either the provided credentials or a dedicated bind user?

**Comment by tazjin** [comment]
> If the server prohibits anonymous binds, murmur_ldap_auth will no longer work, correct?

Yep!

> Why not simply try to bind with either the provided credentials or a dedicated bind user?

It wasn't necessary for [our setup](https://github.com/Goonswarm/infrastructure/tree/master/slapd), as LDAP itself was never exposed to anything outside of our cluster.

Note that the EVE corporation for which this software was written doesn't exist anymore, so the repos under this organisation are unmaintained. Still it should be trivial to add authenticated lookup binds if you need them :-)

**Comment by ghost** [comment]
> it should be trivial to add authenticated lookup binds

I guess I might just try to see what I can do then!

Thanks for your quick and detailed help :)
